dist: focal
group: dev
script:
- sudo cat /etc/docker/daemon.json
#- sudo rm -f /etc/docker/daemon.json
#- sudo systemctl restart docker
- curl -I https://registry-1.travis-ci.com
- nslookup registry-1.travis-ci.com
#- while true ; do curl -I https://registry-1.travis-ci.com ; done
- docker version
- docker pull alpine:latest
- docker pull golang:1.13-alpine3.10
